### ISSUE TITLE
Search Box Feedback

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#82] opened 2016-02-09 14:41 UTC
Comments from Tomasz Koralewski:
- Consider starting search procedure after pressing the “enter” key
- After clearing the search results in the the Search box, the drop down menus don’t work correctly
  E.g.: type “temperature”, click “Search”, click “(Clear this search)” – drop down menus cannot be clicked, and excessive message appears:

![image](https://cloud.githubusercontent.com/assets/886682/12919070/5fafdbf8-cf10-11e5-9805-7cdda1cbfe75.png)

The drop-down menus show when mouse moves over but disappear when mouse moves down and cannot be clicked.  The Search box remains underlined. 

Note: this behavior occurs with Windows 7 Professional with Service Pack 1, Internet Explorer v. 11
I am not able to replicate using Chrome 48.0.2564.103 m or Firefox 43.0.1 with Windows 10.

**Comment by daviswx** [comment] 2016-02-09 14:58
I am also able to replicate this on IE but not on Chrome and Firefox.  It's not giving any errors in IE, but maybe that browser treats the menu navigation functions slightly differently.  I will explore more...

**Comment by daviswx** [comment] 2016-02-11 15:13
How to trigger the Submit button when 'Enter' is clicked:
http://stackoverflow.com/questions/12955222/how-to-trigger-html-button-when-you-press-enter-in-textbox

**Comment by daviswx** [comment] 2016-02-11 18:11
The search box will now submit when the Enter key is pressed.

The bug with the search results menu not hiding in IE should also be fixed.  It required a bit of a workaround in my code, but it seems to be working correctly in all three browsers I tried.

**Comment by hadinon** [comment] 2016-02-11 18:52
Great! The bug is fixed when I tested it with Edge, too. :+1:

**Comment by daviswx** [comment] 2016-03-08 19:59
Still one bug with it: After searching, if you scroll over one of the other menu titles, they show up behind the search results.  Could fix by changing the search results box z-index.

May also want to try putting the search results box in a different color.

Once this is fixed, turn off the search box and expand the other menu items horizontally.

**Comment by daviswx** [comment] 2016-03-09 14:25
This bug should be fixed.  Could you check on your end to confirm?

Once that's done, I will comment out the search box until we add more tools and want to put it back in.

**Comment by hadinon** [comment] 2016-03-10 21:14
It seems to be working in Chrome but not in Firefox or Edge and I cleared my cache! Which browsers did you try it in? 

It's also doing that weird thing with the text that we discussed at the eye tracking meeting. I think you said you changed it to clear on focus but I might be remembering the terminology wrong. Are you able to replicate?

**Comment by daviswx** [comment] 2016-03-11 15:53
It was also working for me in Chrome but not in Firefox.  Annoyingly, each browser handles some JQuery functions a bit differently, which is the cause of this bug and the previous one Tomasz mentioned.

I made some changes and it's working for me now in Chrome, Firefox, and IE.  Could you check all the browsers on your end and make sure it's working in them?

Also, which text box is doing weird things for you?  Is it the search box?  Because it is set to clear the filler text on focus -- in fact, the search box always has been that way -- and I'm not able to replicate the problem with entering text mid-string in any browsers.  After our meeting last week, I changed the lat/lon boxes to also use that function, so you may want to check them as well.

**Comment by hadinon** [comment] 2016-03-21 16:29
OK, it looks to work across all browsers now. :+1: 

Turns out the weird text box issue is only occurring with my rather buggy desktop version of IE so that's probably an IE issue not a DSS issue.

**Closed as completed** 2016-03-21 16:36 UTC
Labels: bug, enhancement

**Comment by daviswx** [comment] 2016-03-28 19:01
Now that the bugs seem to be fixed, I have turned off the search box and enlarged the other menu items.  The search box can easily be re-enabled once we add more tools.
